### ISSUE TITLE
IndexError: list index out of range. dedup_cmd is blank

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#20]
```
Traceback (most recent call last):
  File "/home/ns5bc/code/peppro/pipelines/peppro.py", line 2968, in <module>
    sys.exit(main())
  File "/home/ns5bc/code/peppro/pipelines/peppro.py", line 1676, in main
    outfolder=param.outfolder)
  File "/home/ns5bc/code/peppro/pipelines/peppro.py", line 1024, in _process_fastq
    follow=ngstk.check_trim(processed_fastq, False, None))
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pypiper/manager.py", line 786, in run
    self.callprint(cmd, shell, lock_file, nofail, container)  # Run command
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pypiper/manager.py", line 940, in callprint
    processes.append(psutil.Popen(preexec_fn=os.setsid, **param_list[i]))
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/psutil/__init__.py", line 1310, in __init__
    self.__subproc = subprocess.Popen(*args, **kwargs)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/subprocess.py", line 1228, in _execute_child
    executable = args[0]
IndexError: list index out of range
```

Caused by this line:

https://github.com/databio/peppro/blob/31224c5e7530bbe76079974af661418e70791604/pipelines/peppro.py#L1021-L1022

because `dedup_cmd` is empty:

https://github.com/databio/peppro/blob/31224c5e7530bbe76079974af661418e70791604/pipelines/peppro.py#L374

which leads to a pipe to another pipe, which is broken:

```
cutadapt -j 8 -m 18 -a TGGAATTCTCGGGTGCCAAGG /sfs/lustre/allocations/shefflab/processed/ppqc_test/results_pipeline/GSM3309956/fastq/GSM3309956_R1.fastq |  | seqtk trimfq -b 0 -L 30 - | seqtk seq -r - > /sfs/lustre/allocations/shefflab/processed/ppqc_test/results_pipeline/GSM3309956/fastq/GSM3309956_R1_processed.fastq 
```

**Comment by nsheff** [comment]
I think this didn't come up because previously @jpsmith5 was running everything with default umi_len set to 8. But now I'm running with umi_len set to 0 so it's going into untested parts of the code.

**Comment by nsheff** [comment]
So this line is saying: 

```
if not read2 and not args.umi_len <= 0:
```
If it's single end, and there are UMIs, do something... otherwise: set `dedup_cmd` = "".

But the later we say:

```
    # Put it all together
    if read2:
        process_fastq_cmd2 = build_command([
            adapter_cmd, "|", trim_cmd2])
        #print("process_fastq_cmd2: {}".format(process_fastq_cmd2))
        pm.run(process_fastq_cmd2, trimmed_fastq_R2)
        cp_cmd = ("cp " + trimmed_fastq_R2 + " " + trimmed_dups_fastq_R2)
        pm.run(cp_cmd, trimmed_dups_fastq_R2)
        return trimmed_fastq_R2, trimmed_dups_fastq_R2
    else:
        if args.complexity and args.umi_len > 0:
            pm.run([adapter_cmd, dedup_cmd, trim_cmd_nodedup],
                   trimmed_fastq, follow=report_fastq)
            pm.run(trim_cmd1, processed_fastq,
                   follow=ngstk.check_trim(processed_fastq, False, None))
            pm.clean_add(noadap_fastq)
            pm.clean_add(dedup_fastq)
            pm.clean_add(trimmed_fastq)
            return processed_fastq, trimmed_fastq
        else:
            process_fastq_cmd = build_command([
                adapter_cmd, "|", dedup_cmd, "|", trim_cmd1])
            pm.run(process_fastq_cmd, processed_fastq,
               follow=ngstk.check_trim(

```

That says if it's single end, and there's no UMI (which is the situation we're in), then use the `dedup_cmd` previously set at "".

So, clearly a logical error in here somewhere. Unfortunately I do not know how to fix this.

**Comment by nsheff** [comment]
One solution is to just remove that command from the pipe:

```
            process_fastq_cmd = build_command([
                adapter_cmd, "|", trim_cmd1])
```

Then things continue in the pipeline. Is that correct?

So, with No UMIs, and single-end, we should not run any deduplicator? Is that the solution?

**Comment by jpsmith5** [comment]
Yes that is the solution. I thought I had the umi_len 0 working as I thought some of the samples I had run used that setting. Could check the relevant processed folders in /project. But yes, should not deduplicate in that scenario

**Comment by nsheff** [comment]
The umi_len argument was not being correctly passed to the pipeline, so they all ran with the default, which was `umi_len=8`.

**Comment by jpsmith5** [comment]
Appears to be resolved, particularly with reworking of fastq processing steps.
