### ISSUE TITLE
UnboundLocalError: local variable 'unmap_fq1_dups' referenced before assignment

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#22]
```
Traceback (most recent call last):
  File "/home/nsheff/code/peppro/pipelines/peppro.py", line 2969, in <module>
    sys.exit(main())
  File "/home/nsheff/code/peppro/pipelines/peppro.py", line 1657, in main
    unmap_fq1_dups + " " + unmap_fq2_dups)
UnboundLocalError: local variable 'unmap_fq1_dups' referenced before assignment
```

**Comment by nsheff** [comment]
This is related to #20, I think... there's another error here, as unmap_fq1_dups is never set if umi_len is 0:

https://github.com/databio/peppro/blob/31224c5e7530bbe76079974af661418e70791604/pipelines/peppro.py#L1608-L1619

**Comment by nsheff** [comment]
Related to #24

**Comment by nsheff** [comment]
but only for paired end reads....

My samples with umi_len =0 have now completed successfully for single-end reads, but this bug is preventing them from completing for paired-end reads.

**Comment by nsheff** [comment]
@jpsmith5 what should happen here? it's coming from these lines of code:

https://github.com/databio/peppro/blob/31224c5e7530bbe76079974af661418e70791604/pipelines/peppro.py#L1655-L1656

but this command doesn't make sense in situation of paired end, umi_len=0, because there are no unmap_fq1_dups (although there are unmap_fq2_dups for some reason).

**Comment by jpsmith5** [comment]
Okay. Yeah, if there is no UMI, there can be no deduplication.  Without NON-deduplicated reads, you can't produce the library complexity plots (the args.complexity).  It may be possible to check for umi_len=0 and then override args.complexity to false to solve this.

**Comment by jpsmith5** [comment]
Sorry, both DEduplicated and NON for library complexity.

**Comment by jpsmith5** [comment]
Basically, we should exclude this command when umi_len=0.  Because we shouldn't need to produce the 'dups' files.

**Comment by nsheff** [comment]
got it. thanks
