### ISSUE TITLE
numpy version incompatibility

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#23]
reported by @guertinlab

```
...
'chr11_KI270832v1_alt', 'chr22_KI270736v1_random', 'chr8_KI270822v1_alt', 'chr2_KI270771v1_alt', 'chr22_KI270738v1_random', 'chr22', 'chr20', 'chr21', 'chr22_KI270876v1_alt', 'chr18_GL383568v1_alt']
Reduce step (merge files)...
Merging 189 files into output file: '/Users/guertinlab/Desktop/vcap/output/shVector_rep1/QC_hg38/shVector_rep1_bamQC.tsv'
Traceback (most recent call last):
  File "/Users/guertinlab/Downloads/peppro-master/tools/bamQC.py", line 253, in <module>
    qc.combine(good_chromosomes)
  File "/Users/guertinlab/Downloads/peppro-master/tools/bamQC.py", line 193, in combine
    chrStats = np.load(temp_files[i] + '.npy')
  File "/Library/Python/2.7/site-packages/numpy-1.16.3-py2.7-macosx-10.13-intel.egg/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/Library/Python/2.7/site-packages/numpy-1.16.3-py2.7-macosx-10.13-intel.egg/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
</pre>
```

downgraded from 
numpy
Version: 1.16.3
to
Version: 1.16.1

This solved my latest issue thanks to: https://stackoverflow.com/questions/55890813/how-to-fix-object-arrays-cannot-be-loaded-when-allow-pickle-false-for-imdb-loa

**Comment by nsheff** [comment]
this is not a problem with pararead, but with bamQC.py in peppro.

**Comment by jpsmith5** [comment]
Working as of numpy version 1.17.4 so appears to be resolved.
