### ISSUE TITLE
bedtools not found

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#53]
using bulker run databio/peppro ... I get this error:

```
The following required tool(s) are not callable: bedtools ${PICARD}

### Pipeline failed at:  (02-20 16:50:17) elapsed: 0.0 _TIME_

Total time: 0:00:00
Failure reason: Missing required tools. See message above.
Traceback (most recent call last):
  File "/home/ns5bc/code/peppro/pipelines/peppro.py", line 3743, in <module>
    sys.exit(main())
  File "/home/ns5bc/code/peppro/pipelines/peppro.py", line 1883, in main
    pm.fail_pipeline(RuntimeError(err_msg))
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
RuntimeError: Missing required tools. See message above.
[ns5bc@udc-ba34-36:~/code/danG] bedtools
-bash: bedtools: command not found
[ns5bc@udc-ba34-36:~/code/danG] bulker run databio/peppro bedtools --help
Bulker config: /project/shefflab/rivanna_config/bulker.yaml
Activating crate: databio/peppro

/bin/sh: bedtools: command not found
```

**Comment by nsheff** [comment]
https://github.com/databio/hub.bulker.io/commit/6b8d91bab3357cb854762674d632271905367a9f

**Comment by jpsmith5** [comment]
Sorry. Just saw you were fixing these things in dev.  Let me know when you're done and I'll re-release.

**Comment by nsheff** [comment]
I'm running it through some tests now. I think it's working...

not sure what to do about the annoying R installs though

**Comment by jpsmith5** [comment]
Once you've confirmed it's all working, we should be set to add everything back to master and release.  Let me know if you hit any more hiccups.

**Comment by nsheff** [comment]
this one looks like it's working in my hands now,
