### ISSUE TITLE
looper run errors

### ISSUE THREAD

**Issue by Dale12138** [databio/peppro#76]
Hi,
I have encountered errors even in the very first step (dry run the example). I would appreciate it so much if you can drop me some hints on how to fix this!
**my code** looper run  peppro_test.yaml -d
**printouts**
Command: run (Looper version: 0.12.6)
Reading sample annotations sheet: '/hpf/largeprojects/mdwilson/liangxi/projects/rela/chroseq/analysis/peppro/test/peppro_test.csv'
Storing sample table from file '/hpf/largeprojects/mdwilson/liangxi/projects/rela/chroseq/analysis/peppro/test/peppro_test.csv'
Traceback (most recent call last):
  File "/hpf/tools/centos6/python/2.7.9/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/looper/looper.py", line 798, in main
    file_checks=args.file_checks, compute_env_file=getattr(args, 'env', None))
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/looper/project.py", line 40, in __init__
    no_compute_exception=RuntimeError, **kwargs)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/peppy/project.py", line 268, in __init__
    self._set_basic_samples()
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/peppy/project.py", line 1145, in _set_basic_samples
    self._samples = self._prep_samples()
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/peppy/project.py", line 1086, in _prep_samples
    sample = Sample(row.dropna(), prj=self)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/peppy/sample.py", line 154, in __init__
    series = series.to_dict(OrderedDict)
TypeError: to_dict() takes exactly 1 argument (2 given)

P.S I ve been using python/2.7.9

**Comment by jpsmith5** [comment]
Hey @Dale12138, 
As the python people no longer are updating and supporting python2, so follows most of our tools. Can you give it an install with python3 and see how it goes? I’ll also make a note to update our documentation to emphasize this going forward. 

Let us know if you hit a snag and we can definitely help troubleshoot.

**Comment by Dale12138** [comment]
Oh, I didn't notice this python2 vs python3 discrepency here. I ll try to update the tools and dependencies to python3 and let you know! Thanks!

**Comment by nsheff** [comment]
@Dale12138 were you able to get this to work?

**Comment by nsheff** [comment]
Please reopen if you run into similar issues again.
